# Generated by Django 6.0.3 on 2026-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
            ],
        ),
    ]
